"""Constitutive-consistent Hierarchical Potential Graph Neural Simulator."""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from valgraphnet.config import get_cfg
from valgraphnet.hierarchy import HierarchicalScalarVectorProcessor, TopologyHierarchy
from valgraphnet.mechanics import (
    AnalyticPotential,
    assemble_internal_force,
    deformation_gradient,
    invariants,
    project_cell_to_nodes,
    semi_implicit_step,
    von_mises,
)


@dataclass
class CHPStatic:
    reference_position: torch.Tensor
    cells: torch.Tensor
    mesh_edge_index: torch.Tensor
    dm_inv: torch.Tensor
    volume: torch.Tensor
    shape_gradients: torch.Tensor
    lumped_mass: torch.Tensor
    fixed_mask: torch.Tensor
    prescribed_mask: torch.Tensor
    material_features: torch.Tensor
    fiber_direction: torch.Tensor
    hierarchy: TopologyHierarchy

    @property
    def num_nodes(self) -> int:
        return int(self.reference_position.shape[0])


@dataclass
class CHPState:
    position: torch.Tensor
    velocity: torch.Tensor


@dataclass
class PhysicalStep:
    next_position: torch.Tensor
    next_velocity: torch.Tensor
    acceleration: torch.Tensor
    nodal_stress: torch.Tensor
    cell_stress_tensor: torch.Tensor
    internal_force: torch.Tensor
    contact_force: torch.Tensor
    damping_force: torch.Tensor
    residual_force: torch.Tensor
    energy_diagnostics: dict[str, torch.Tensor]

    def legacy_predictions(self, state: CHPState) -> dict[str, torch.Tensor]:
        return {
            "delta_u": self.next_position - state.position,
            "delta_v": self.next_velocity - state.velocity,
            "accel": self.acceleration,
            "stress": self.nodal_stress,
        }


@dataclass
class ConstitutiveFields:
    """Fields generated by the shared potential at one configuration."""

    deformation: torch.Tensor
    first_piola: torch.Tensor
    cauchy_stress: torch.Tensor
    energy_density: torch.Tensor
    internal_force: torch.Tensor
    inversion_barrier: torch.Tensor


class VectorChannelLinear(nn.Module):
    """Mix vector channels without mixing Cartesian coordinates."""

    def __init__(self, input_channels: int, output_channels: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.empty(output_channels, input_channels))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        return torch.einsum("oc,nci->noi", self.weight, value)


class CellNodeBlock(nn.Module):
    def __init__(self, node_dim: int = 96, cell_dim: int = 64) -> None:
        super().__init__()
        self.cell_update = nn.Sequential(
            nn.Linear(cell_dim + node_dim, cell_dim),
            nn.SiLU(),
            nn.Linear(cell_dim, cell_dim),
        )
        self.node_update = nn.Sequential(
            nn.Linear(node_dim + cell_dim, node_dim),
            nn.SiLU(),
            nn.Linear(node_dim, node_dim),
        )
        self.cell_norm = nn.LayerNorm(cell_dim)
        self.node_norm = nn.LayerNorm(node_dim)

    def forward(
        self, node: torch.Tensor, cell: torch.Tensor, cells: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        node_at_cell = node[cells].mean(dim=1)
        cell = self.cell_norm(cell + self.cell_update(torch.cat([cell, node_at_cell], 1)))
        messages = cell[:, None, :].expand(-1, 4, -1)
        node_message = node.new_zeros((node.shape[0], cell.shape[1]))
        node_message.index_add_(0, cells.reshape(-1), messages.reshape(-1, cell.shape[1]))
        degree = torch.bincount(cells.reshape(-1), minlength=node.shape[0]).to(node.dtype)
        node_message = node_message / degree.clamp_min(1.0)[:, None]
        node = self.node_norm(node + self.node_update(torch.cat([node, node_message], 1)))
        return node, cell


class PairForceHeads(nn.Module):
    """Non-negative damping/contact magnitudes assembled as pair forces."""

    def __init__(self, scalar_dim: int) -> None:
        super().__init__()
        symmetric_dim = 2 * scalar_dim + 4
        self.damping = nn.Sequential(
            nn.Linear(symmetric_dim, scalar_dim), nn.SiLU(), nn.Linear(scalar_dim, 1)
        )
        self.contact = nn.Sequential(
            nn.Linear(symmetric_dim, scalar_dim), nn.SiLU(), nn.Linear(scalar_dim, 2)
        )

    @staticmethod
    def invariants(
        scalar: torch.Tensor,
        position: torch.Tensor,
        velocity: torch.Tensor,
        pairs: torch.Tensor,
        reference_position: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        src, dst = pairs
        relative = position[dst] - position[src]
        distance = torch.linalg.vector_norm(relative, dim=1, keepdim=True).clamp_min(1.0e-8)
        direction = relative / distance
        relative_velocity = velocity[dst] - velocity[src]
        normal_velocity = (relative_velocity * direction).sum(1, keepdim=True)
        if reference_position is None:
            stretch = torch.zeros_like(distance)
        else:
            reference_length = torch.linalg.vector_norm(
                reference_position[dst] - reference_position[src], dim=1, keepdim=True
            ).clamp_min(1.0e-8)
            stretch = distance / reference_length - 1.0
        features = torch.cat(
            [
                scalar[src] + scalar[dst],
                (scalar[src] - scalar[dst]).abs(),
                distance,
                stretch,
                normal_velocity,
                torch.linalg.vector_norm(relative_velocity, dim=1, keepdim=True),
            ],
            dim=1,
        )
        return features, direction, relative_velocity, normal_velocity

    @staticmethod
    def scatter_pair(force_on_src: torch.Tensor, pairs: torch.Tensor, count: int) -> torch.Tensor:
        result = force_on_src.new_zeros((count, 3))
        result.index_add_(0, pairs[0], force_on_src)
        result.index_add_(0, pairs[1], -force_on_src)
        return result

    @staticmethod
    def reduced_mass(mass: torch.Tensor, pairs: torch.Tensor) -> torch.Tensor:
        """Symmetric pair mass keeps learned accelerations mesh-scale stable."""

        nodal_mass = mass.reshape(-1)
        source_mass = nodal_mass[pairs[0]]
        target_mass = nodal_mass[pairs[1]]
        return (
            2.0
            * source_mass
            * target_mass
            / (source_mass + target_mass).clamp_min(torch.finfo(nodal_mass.dtype).tiny)
        )[:, None]

    @staticmethod
    def pair_normalization(pairs: torch.Tensor, count: int) -> torch.Tensor:
        """Mean-aggregate pair impulses without breaking action--reaction."""

        degree = torch.bincount(
            torch.cat([pairs[0], pairs[1]]), minlength=int(count)
        )
        pair_degree = torch.maximum(degree[pairs[0]], degree[pairs[1]])
        return pair_degree.clamp_min(1).to(dtype=torch.float32)[:, None].reciprocal()

    def mesh_damping(
        self,
        scalar: torch.Tensor,
        position: torch.Tensor,
        velocity: torch.Tensor,
        mesh_pairs: torch.Tensor,
        reference_position: torch.Tensor,
        nodal_mass: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        if mesh_pairs.numel() == 0:
            zero = position.new_zeros((position.shape[0], 3))
            return zero, position.new_zeros(())
        features, direction, _, normal_velocity = self.invariants(
            scalar, position, velocity, mesh_pairs, reference_position
        )
        coefficient = F.softplus(self.damping(features))
        force_src = coefficient * normal_velocity * direction
        pair_mass = None
        pair_weight = self.pair_normalization(mesh_pairs, position.shape[0]).to(
            force_src.dtype
        )
        force_src = force_src * pair_weight
        if nodal_mass is not None:
            pair_mass = self.reduced_mass(nodal_mass, mesh_pairs)
            force_src = force_src * pair_mass
        force = self.scatter_pair(force_src, mesh_pairs, position.shape[0])
        dissipation_density = coefficient * normal_velocity.square() * pair_weight
        if pair_mass is not None:
            dissipation_density = dissipation_density * pair_mass
        dissipation = dissipation_density.sum()
        return force, dissipation

    def contact_force(
        self,
        scalar: torch.Tensor,
        position: torch.Tensor,
        velocity: torch.Tensor,
        contact_pairs: torch.Tensor,
        radius: float,
        nodal_mass: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if contact_pairs.numel() == 0:
            zero = position.new_zeros((position.shape[0], 3))
            scalar_zero = position.new_zeros(())
            return zero, scalar_zero, scalar_zero
        features, direction, relative_velocity, normal_velocity = self.invariants(
            scalar, position, velocity, contact_pairs
        )
        raw = self.contact(features)
        penetration = ((float(radius) - features[:, -4:-3]) / max(float(radius), 1.0e-8)).clamp_min(0.0)
        normal_magnitude = F.softplus(raw[:, :1]) * penetration
        normal_force_src = -normal_magnitude * direction
        tangential_velocity = relative_velocity - normal_velocity * direction
        tangential_coefficient = F.softplus(raw[:, 1:2])
        tangential_force_src = tangential_coefficient * tangential_velocity
        force_src = normal_force_src + tangential_force_src
        pair_mass = None
        pair_weight = self.pair_normalization(contact_pairs, position.shape[0]).to(
            force_src.dtype
        )
        force_src = force_src * pair_weight
        if nodal_mass is not None:
            pair_mass = self.reduced_mass(nodal_mass, contact_pairs)
            force_src = force_src * pair_mass
        force = self.scatter_pair(force_src, contact_pairs, position.shape[0])
        dissipation_density = (
            tangential_coefficient
            * tangential_velocity.square().sum(1, keepdim=True)
            * pair_weight
        )
        if pair_mass is not None:
            dissipation_density = dissipation_density * pair_mass
        dissipation = dissipation_density.sum()
        return force, penetration.max(), dissipation


class CHPGNS(nn.Module):
    """Hierarchical potential simulator whose stress and dynamics share mechanics."""

    checkpoint_schema_version = 2

    def __init__(self, cfg: dict[str, Any], material_dim: int = 0) -> None:
        super().__init__()
        model_cfg = cfg.get("model", {})
        self.scalar_dim = int(model_cfg.get("scalar_dim", 96))
        self.vector_dim = int(model_cfg.get("vector_dim", 16))
        self.cell_dim = int(model_cfg.get("cell_dim", 64))
        self.material_dim = int(material_dim)
        self.contact_radius = float(get_cfg(cfg, "contact.radius", 0.03))
        self.contact_substeps = int(model_cfg.get("contact_substeps", 2))
        self.residual_limit = float(model_cfg.get("residual_force_limit", 0.1))
        initial_stress_scale = float(model_cfg.get("initial_stress_scale", 1.0))
        initial_mass_scale = float(model_cfg.get("initial_mass_scale", 1.0))
        initial_contact_scale = float(model_cfg.get("initial_contact_scale", 1.0e-3))
        initial_damping_scale = float(model_cfg.get("initial_damping_scale", 0.1))
        if min(
            initial_stress_scale,
            initial_mass_scale,
            initial_contact_scale,
            initial_damping_scale,
        ) <= 0.0:
            raise ValueError("initial physical scales must be positive")
        self.log_stress_scale = nn.Parameter(torch.tensor(math.log(initial_stress_scale)))
        self.log_mass_scale = nn.Parameter(torch.tensor(math.log(initial_mass_scale)))
        self.log_contact_scale = nn.Parameter(torch.tensor(math.log(initial_contact_scale)))
        self.log_damping_scale = nn.Parameter(torch.tensor(math.log(initial_damping_scale)))

        self.node_encoder = nn.Sequential(
            nn.Linear(6, self.scalar_dim),
            nn.SiLU(),
            nn.Linear(self.scalar_dim, self.scalar_dim),
            nn.LayerNorm(self.scalar_dim),
        )
        self.vector_encoder = VectorChannelLinear(3, self.vector_dim)
        self.processor = HierarchicalScalarVectorProcessor(
            self.scalar_dim,
            self.vector_dim,
            activation_checkpointing=bool(
                model_cfg.get("activation_checkpointing", True)
            ),
        )
        cell_input_dim = self.scalar_dim + 6 + self.material_dim
        self.cell_encoder = nn.Sequential(
            nn.Linear(cell_input_dim, self.cell_dim),
            nn.SiLU(),
            nn.Linear(self.cell_dim, self.cell_dim),
            nn.LayerNorm(self.cell_dim),
        )
        self.cell_blocks = nn.ModuleList(
            [CellNodeBlock(self.scalar_dim, self.cell_dim) for _ in range(4)]
        )
        self.force_heads = PairForceHeads(self.scalar_dim)
        self.residual_channel = VectorChannelLinear(self.vector_dim, 1)
        self.potential = AnalyticPotential(
            order=int(model_cfg.get("potential_order", 2)),
            fiber_order=int(model_cfg.get("fiber_order", 0)),
            inversion_stiffness=float(model_cfg.get("inversion_stiffness", 10.0)),
            minimum_j=float(model_cfg.get("minimum_j", 0.0)),
        )
        self.material_scale = (
            nn.Sequential(nn.Linear(self.material_dim, 32), nn.SiLU(), nn.Linear(32, 1))
            if self.material_dim
            else None
        )

    def constitutive_fields(
        self,
        static: CHPStatic,
        position: torch.Tensor,
        *,
        deformation: torch.Tensor | None = None,
    ) -> ConstitutiveFields:
        """Evaluate stress, energy, and internal force from the same potential."""

        position = position.float()
        if deformation is None:
            deformation = deformation_gradient(position, static.cells, static.dm_inv)
        material = static.material_features.float()
        if material.shape[1] != self.material_dim:
            raise ValueError(
                f"Expected {self.material_dim} material features, got {material.shape[1]}"
            )
        fiber = static.fiber_direction if self.potential.fiber_order else None
        response = self.potential(deformation, fiber_direction=fiber)
        stress_scale = self.log_stress_scale.clamp(-20.0, 30.0).exp()
        if self.material_scale is None:
            scale = torch.ones(
                (static.cells.shape[0], 1),
                device=position.device,
                dtype=position.dtype,
            )
        else:
            scale = F.softplus(self.material_scale(material)).float() + 1.0e-6
        first_piola = response.first_piola * scale[:, :, None] * stress_scale
        cauchy = response.cauchy_stress * scale[:, :, None] * stress_scale
        energy_density = response.energy_density * scale[:, 0] * stress_scale
        internal = assemble_internal_force(
            first_piola,
            static.cells,
            static.volume,
            static.shape_gradients,
            static.num_nodes,
        )
        return ConstitutiveFields(
            deformation=deformation,
            first_piola=first_piola,
            cauchy_stress=cauchy,
            energy_density=energy_density,
            internal_force=internal,
            inversion_barrier=response.inversion_barrier,
        )

    def nodal_stress_at(
        self, static: CHPStatic, position: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Return potential-derived nodal von-Mises and full cell stress."""

        fields = self.constitutive_fields(static, position)
        cell_vm = von_mises(fields.cauchy_stress)
        nodal = project_cell_to_nodes(
            cell_vm[:, None],
            static.cells,
            static.num_nodes,
            weights=static.volume,
        )
        return nodal, fields.cauchy_stress

    def forward(
        self,
        static: CHPStatic,
        state: CHPState,
        *,
        contact_pairs: torch.Tensor | None = None,
        external_force: torch.Tensor | None = None,
        dt: float | torch.Tensor = 1.0,
        time_fraction: float | torch.Tensor = 0.0,
        prescribed_position: torch.Tensor | None = None,
        prescribed_velocity: torch.Tensor | None = None,
    ) -> PhysicalStep:
        position = state.position.float()
        velocity = state.velocity.float()
        reference = static.reference_position.float()
        displacement = position - reference
        if external_force is None:
            external_force = torch.zeros_like(position)
        else:
            external_force = external_force.float()
        time = torch.as_tensor(time_fraction, device=position.device, dtype=position.dtype)
        scalar_input = torch.stack(
            [
                static.fixed_mask.float(),
                static.prescribed_mask.float(),
                (~(static.fixed_mask | static.prescribed_mask)).float(),
                torch.log1p(static.lumped_mass.float().reshape(-1)),
                torch.sin(2.0 * torch.pi * time).expand(position.shape[0]),
                torch.cos(2.0 * torch.pi * time).expand(position.shape[0]),
            ],
            dim=1,
        )
        scalar = self.node_encoder(scalar_input)
        vector_input = torch.stack([displacement, velocity, external_force], dim=1)
        vector = self.vector_encoder(vector_input)
        scalar, vector = self.processor(scalar, vector, position, static.hierarchy)

        deformation = deformation_gradient(position, static.cells, static.dm_inv)
        strain = invariants(deformation)
        invariant_features = torch.stack(
            [
                strain.i1_bar - 3.0,
                strain.i2_bar - 3.0,
                strain.j - 1.0,
                torch.log(strain.j.clamp_min(1.0e-8)),
                strain.i1 - 3.0,
                strain.i2 - 3.0,
            ],
            dim=1,
        )
        cell_node = scalar[static.cells].mean(1)
        material = static.material_features.float()
        if material.shape[1] != self.material_dim:
            raise ValueError(
                f"Expected {self.material_dim} material features, got {material.shape[1]}"
            )
        cell = self.cell_encoder(torch.cat([cell_node, invariant_features, material], 1))
        for block in self.cell_blocks:
            scalar, cell = block(scalar, cell, static.cells)

        initial_fields = self.constitutive_fields(
            static, position, deformation=deformation
        )
        mesh_pairs = unique_undirected_pairs(static.mesh_edge_index, static.num_nodes)
        if contact_pairs is None:
            contact_pairs = position.new_zeros((2, 0), dtype=torch.long)
        contact_pairs = unique_undirected_pairs(contact_pairs, static.num_nodes)
        mass_scale = self.log_mass_scale.clamp(-20.0, 40.0).exp()
        nodal_mass = static.lumped_mass.reshape(-1) * mass_scale
        contact_scale = self.log_contact_scale.clamp(-20.0, 10.0).exp()
        damping_scale = self.log_damping_scale.clamp(-20.0, 10.0).exp()
        raw_residual = self.residual_channel(vector)[:, 0]
        residual_norm = torch.linalg.vector_norm(raw_residual, dim=1, keepdim=True)
        residual = (
            self.residual_limit
            * torch.tanh(residual_norm)
            * raw_residual
            / residual_norm.clamp_min(1.0e-8)
        )
        activity = (
            torch.linalg.vector_norm(displacement, dim=1, keepdim=True)
            + torch.linalg.vector_norm(velocity, dim=1, keepdim=True)
            + torch.linalg.vector_norm(external_force, dim=1, keepdim=True)
        )
        residual = residual * torch.tanh(activity)
        active_prescribed_mask = (
            static.prescribed_mask
            if bool(static.prescribed_mask.any().item())
            else None
        )
        step_dt = torch.as_tensor(dt, device=position.device, dtype=position.dtype)
        substep_dt = step_dt / max(self.contact_substeps, 1)
        current_position = position
        current_velocity = velocity
        external_work = position.new_zeros(())
        boundary_work = position.new_zeros(())
        damping_dissipation = position.new_zeros(())
        contact_dissipation = position.new_zeros(())
        max_penetration = position.new_zeros(())
        damping = torch.zeros_like(position)
        contact = torch.zeros_like(position)
        total_force = torch.zeros_like(position)
        current_fields = initial_fields
        for substep in range(max(self.contact_substeps, 1)):
            if substep:
                current_fields = self.constitutive_fields(static, current_position)
            damping, damping_rate = self.force_heads.mesh_damping(
                scalar,
                current_position,
                current_velocity,
                mesh_pairs,
                reference,
                nodal_mass,
            )
            contact, penetration, contact_rate = self.force_heads.contact_force(
                scalar,
                current_position,
                current_velocity,
                contact_pairs,
                self.contact_radius,
                nodal_mass,
            )
            damping = damping * damping_scale
            damping_rate = damping_rate * damping_scale
            contact = contact * contact_scale
            contact_rate = contact_rate * contact_scale
            max_penetration = torch.maximum(max_penetration, penetration)
            total_force = (
                current_fields.internal_force
                + damping
                + contact
                + residual
                + external_force
            )
            substep_target = None
            if prescribed_position is not None:
                fraction = float(substep + 1) / max(self.contact_substeps, 1)
                substep_target = position + fraction * (
                    prescribed_position.float() - position
                )
            integrated = semi_implicit_step(
                current_position,
                current_velocity,
                total_force,
                nodal_mass,
                substep_dt,
                substeps=1,
                fixed_mask=static.fixed_mask,
                prescribed_mask=active_prescribed_mask,
                prescribed_position=substep_target,
                prescribed_velocity=prescribed_velocity,
            )
            substep_displacement = integrated.position - current_position
            external_work = external_work + (external_force * substep_displacement).sum()
            if active_prescribed_mask is not None:
                reaction = (
                    nodal_mass[:, None] * integrated.acceleration - total_force
                )
                boundary_work = boundary_work + (
                    reaction[active_prescribed_mask]
                    * substep_displacement[active_prescribed_mask]
                ).sum()
            damping_dissipation = damping_dissipation + damping_rate * substep_dt
            contact_dissipation = contact_dissipation + contact_rate * substep_dt
            current_position = integrated.position
            current_velocity = integrated.velocity

        acceleration = (current_velocity - velocity) / step_dt
        final_fields = self.constitutive_fields(static, current_position)
        kinetic_before = 0.5 * (
            static.lumped_mass.reshape(-1, 1)
            * mass_scale
            * velocity.square()
        ).sum()
        kinetic_after = 0.5 * (
            static.lumped_mass.reshape(-1, 1) * current_velocity.square() * mass_scale
        ).sum()
        potential_before = (static.volume * initial_fields.energy_density).sum()
        next_cell_vm = von_mises(final_fields.cauchy_stress)
        nodal_stress = project_cell_to_nodes(
            next_cell_vm[:, None],
            static.cells,
            static.num_nodes,
            weights=static.volume,
        )
        potential_after = (static.volume * final_fields.energy_density).sum()
        energy_balance = (
            kinetic_after
            + potential_after
            - kinetic_before
            - potential_before
            - external_work
            - boundary_work
            + damping_dissipation
            + contact_dissipation
        )
        return PhysicalStep(
            next_position=current_position,
            next_velocity=current_velocity,
            acceleration=acceleration,
            nodal_stress=nodal_stress,
            cell_stress_tensor=final_fields.cauchy_stress,
            internal_force=initial_fields.internal_force,
            contact_force=contact,
            damping_force=damping,
            residual_force=residual,
            energy_diagnostics={
                "potential": potential_before,
                "potential_after": potential_after,
                "kinetic": kinetic_before,
                "kinetic_after": kinetic_after,
                "external_work": external_work,
                "boundary_work": boundary_work,
                "work_energy_balance": energy_balance,
                "damping_dissipation": damping_dissipation,
                "contact_dissipation": contact_dissipation,
                "max_penetration": max_penetration,
                "negative_j": torch.maximum(
                    initial_fields.inversion_barrier.mean(),
                    final_fields.inversion_barrier.mean(),
                ),
                "residual_norm": residual.square().mean().sqrt(),
                "stress_scale": self.log_stress_scale.clamp(-20.0, 30.0).exp(),
                "mass_scale": mass_scale,
                "contact_scale": contact_scale,
                "damping_scale": damping_scale,
            },
        )


def unique_undirected_pairs(edge_index: torch.Tensor, num_nodes: int) -> torch.Tensor:
    if edge_index.numel() == 0:
        return torch.zeros((2, 0), dtype=torch.long, device=edge_index.device)
    src = torch.minimum(edge_index[0].long(), edge_index[1].long())
    dst = torch.maximum(edge_index[0].long(), edge_index[1].long())
    keep = src != dst
    encoded = torch.unique(src[keep] * int(num_nodes) + dst[keep], sorted=True)
    return torch.stack([encoded // int(num_nodes), encoded % int(num_nodes)], dim=0)


def build_chp_static(
    case,
    device: torch.device | str,
    *,
    hierarchy: TopologyHierarchy | None = None,
    material_dim: int | None = None,
) -> CHPStatic:
    """Move one constitutive case and its cached topology hierarchy to a device."""

    def tensor(value, dtype):
        return torch.from_numpy(np.array(value, copy=True)).to(device=device, dtype=dtype)

    reference = tensor(case.nodes, torch.float32)
    cells = tensor(case.cells, torch.long)
    mesh_edges = tensor(case.mesh_edge_index, torch.long)
    hierarchy = (hierarchy or build_case_hierarchy(case)).to(device)
    material_features = np.array(case.material_features, dtype=np.float32, copy=True)
    if material_dim is not None:
        if material_features.shape[1] > int(material_dim):
            raise ValueError(
                f"{case.case_id}: material feature width exceeds model width "
                f"({material_features.shape[1]} > {material_dim})"
            )
        if material_features.shape[1] < int(material_dim):
            material_features = np.pad(
                material_features,
                ((0, 0), (0, int(material_dim) - material_features.shape[1])),
            )
    return CHPStatic(
        reference_position=reference,
        cells=cells,
        mesh_edge_index=mesh_edges,
        dm_inv=tensor(case.dm_inv, torch.float32),
        volume=tensor(case.reference_volume.reshape(-1), torch.float32),
        shape_gradients=tensor(case.shape_gradients, torch.float32),
        lumped_mass=tensor(case.lumped_mass.reshape(-1), torch.float32),
        fixed_mask=tensor(case.fixed_mask, torch.bool),
        prescribed_mask=tensor(case.prescribed_mask, torch.bool),
        material_features=tensor(material_features, torch.float32),
        fiber_direction=tensor(case.fiber_direction, torch.float32),
        hierarchy=hierarchy,
    )


def build_case_hierarchy(case) -> TopologyHierarchy:
    from valgraphnet.hierarchy import build_topology_hierarchy

    return build_topology_hierarchy(
        case.num_nodes,
        torch.from_numpy(np.array(case.mesh_edge_index, dtype=np.int64, copy=True)),
    )


def radius_contact_pairs(
    position: torch.Tensor,
    mesh_edge_index: torch.Tensor,
    fixed_mask: torch.Tensor,
    radius: float,
    max_neighbors: int = 32,
) -> torch.Tensor:
    """Build exact bounded contact pairs on CUDA using PhysicsNeMo Warp search."""

    if not position.is_cuda:
        raise ValueError("radius_contact_pairs requires CUDA positions")
    from physicsnemo.nn.functional import radius_search

    count = int(position.shape[0])
    points = position.detach().float()
    neighbors = radius_search(
        points,
        points,
        radius=float(radius),
        max_points=count,
        return_dists=False,
        return_points=False,
    ).long()
    sources = torch.arange(count, device=position.device)[:, None].expand_as(neighbors)
    adjacency = torch.zeros((count, count), dtype=torch.bool, device=position.device)
    adjacency[mesh_edge_index[0], mesh_edge_index[1]] = True
    valid = (neighbors != sources) & ~adjacency[sources, neighbors]
    valid &= ~(fixed_mask[sources] & fixed_mask[neighbors])
    distance_sq = ((points[sources] - points[neighbors]) ** 2).sum(-1)
    valid &= distance_sq <= float(radius) ** 2
    distance_sq = distance_sq.masked_fill(~valid, torch.inf)
    keep_count = min(int(max_neighbors), count)
    best_distance, positions = torch.topk(
        distance_sq, keep_count, dim=1, largest=False, sorted=True
    )
    best_neighbors = neighbors.gather(1, positions)
    keep = torch.isfinite(best_distance)
    src = sources[:, :keep_count][keep]
    dst = best_neighbors[keep]
    return unique_undirected_pairs(torch.stack([src, dst]), count)
