"""Constitutive-consistent Hierarchical Potential Graph Neural Simulator."""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Any

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from valgraphnet.config import get_cfg
from valgraphnet.hierarchy import HierarchicalScalarVectorProcessor, TopologyHierarchy
from valgraphnet.mechanics import (
    AnalyticPotential,
    assemble_internal_force,
    deformation_gradient,
    invariants,
    project_cell_to_nodes,
    semi_implicit_step,
    von_mises,
)


@dataclass
class CHPStatic:
    reference_position: torch.Tensor
    cells: torch.Tensor
    mesh_edge_index: torch.Tensor
    dm_inv: torch.Tensor
    volume: torch.Tensor
    shape_gradients: torch.Tensor
    lumped_mass: torch.Tensor
    fixed_mask: torch.Tensor
    prescribed_mask: torch.Tensor
    contact_surface_mask: torch.Tensor
    material_features: torch.Tensor
    fiber_direction: torch.Tensor
    hierarchy: TopologyHierarchy

    @property
    def num_nodes(self) -> int:
        return int(self.reference_position.shape[0])


@dataclass
class CHPState:
    position: torch.Tensor
    velocity: torch.Tensor


@dataclass
class PhysicalStep:
    next_position: torch.Tensor
    next_velocity: torch.Tensor
    acceleration: torch.Tensor
    nodal_stress: torch.Tensor
    cell_stress_tensor: torch.Tensor
    internal_force: torch.Tensor
    contact_force: torch.Tensor
    damping_force: torch.Tensor
    residual_force: torch.Tensor
    energy_diagnostics: dict[str, torch.Tensor]

    def legacy_predictions(self, state: CHPState) -> dict[str, torch.Tensor]:
        return {
            "delta_u": self.next_position - state.position,
            "delta_v": self.next_velocity - state.velocity,
            "accel": self.acceleration,
            "stress": self.nodal_stress,
        }


@dataclass
class ConstitutiveFields:
    """Fields generated by the shared potential at one configuration."""

    deformation: torch.Tensor
    first_piola: torch.Tensor
    cauchy_stress: torch.Tensor
    energy_density: torch.Tensor
    internal_force: torch.Tensor
    inversion_barrier: torch.Tensor


class VectorChannelLinear(nn.Module):
    """Mix vector channels without mixing Cartesian coordinates."""

    def __init__(self, input_channels: int, output_channels: int) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.empty(output_channels, input_channels))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        return torch.einsum("oc,nci->noi", self.weight, value)


class CellNodeBlock(nn.Module):
    """Rotation-equivariant messages on tetrahedron--vertex incidences.

    Cells carry scalar constitutive state.  A cell-to-node vector message can
    only point along the centroid-to-vertex direction, while its learned
    weight depends exclusively on scalar invariants.  Consequently the block
    is translation invariant and O(3)-equivariant without choosing a global
    coordinate frame.
    """

    def __init__(
        self,
        node_dim: int = 96,
        vector_dim: int = 16,
        cell_dim: int = 64,
    ) -> None:
        super().__init__()
        self.node_dim = int(node_dim)
        self.vector_dim = int(vector_dim)
        self.cell_dim = int(cell_dim)
        invariant_dim = self.node_dim + self.cell_dim + 1 + 2 * self.vector_dim
        self.node_to_cell = nn.Sequential(
            nn.Linear(invariant_dim, self.cell_dim),
            nn.SiLU(),
            nn.Linear(self.cell_dim, self.cell_dim),
        )
        self.cell_to_node = nn.Sequential(
            nn.Linear(invariant_dim, self.node_dim),
            nn.SiLU(),
            nn.Linear(self.node_dim, self.node_dim + self.vector_dim),
        )
        self.vector_gate = nn.Sequential(
            nn.Linear(self.node_dim, self.vector_dim), nn.Sigmoid()
        )
        self.cell_norm = nn.LayerNorm(self.cell_dim)
        self.node_norm = nn.LayerNorm(self.node_dim)

    def _incidence_invariants(
        self,
        node: torch.Tensor,
        vector: torch.Tensor,
        cell: torch.Tensor,
        cells: torch.Tensor,
        position: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        vertices_per_cell = int(cells.shape[1])
        centroid = position[cells].mean(dim=1)
        relative = position[cells] - centroid[:, None, :]
        distance = torch.linalg.vector_norm(relative, dim=-1, keepdim=True).clamp_min(
            1.0e-8
        )
        direction = relative / distance
        incidence_vector = vector[cells]
        vector_norm = torch.linalg.vector_norm(incidence_vector, dim=-1)
        vector_projection = (incidence_vector * direction[:, :, None, :]).sum(-1)
        repeated_cell = cell[:, None, :].expand(-1, vertices_per_cell, -1)
        features = torch.cat(
            [
                node[cells],
                repeated_cell,
                distance,
                vector_norm,
                vector_projection,
            ],
            dim=-1,
        )
        return features, direction

    def forward(
        self,
        node: torch.Tensor,
        vector: torch.Tensor,
        cell: torch.Tensor,
        cells: torch.Tensor,
        position: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if cells.ndim != 2 or cells.shape[1] != 4:
            raise ValueError(
                "CellNodeBlock expects tetrahedra [M,4], got "
                f"{tuple(cells.shape)}"
            )
        features, direction = self._incidence_invariants(
            node, vector, cell, cells, position
        )
        cell_delta = self.node_to_cell(features).mean(dim=1)
        cell = self.cell_norm(cell + cell_delta)

        features, direction = self._incidence_invariants(
            node, vector, cell, cells, position
        )
        raw = self.cell_to_node(features)
        scalar_message = raw[..., : self.node_dim].to(node.dtype)
        direction_weight = raw[..., self.node_dim :].to(vector.dtype)
        vector_message = direction_weight[..., None] * direction[:, :, None, :]

        flat_nodes = cells.reshape(-1)
        scalar_aggregate = node.new_zeros(node.shape)
        vector_aggregate = vector.new_zeros(vector.shape)
        scalar_aggregate.index_add_(
            0, flat_nodes, scalar_message.reshape(-1, self.node_dim)
        )
        vector_aggregate.index_add_(
            0,
            flat_nodes,
            vector_message.reshape(-1, self.vector_dim, 3).to(vector.dtype),
        )
        degree = torch.bincount(flat_nodes, minlength=node.shape[0]).to(node.dtype)
        degree = degree.clamp_min(1.0)
        scalar_aggregate = scalar_aggregate / degree[:, None]
        vector_aggregate = vector_aggregate / degree[:, None, None]
        node = self.node_norm(node + scalar_aggregate)
        vector = vector + self.vector_gate(node)[:, :, None] * vector_aggregate
        return node, vector, cell


class PairForceHeads(nn.Module):
    """Non-negative damping/contact magnitudes assembled as pair forces."""

    def __init__(self, scalar_dim: int, tangential_ratio_cap: float = 1.0) -> None:
        super().__init__()
        self.tangential_ratio_cap = float(tangential_ratio_cap)
        if self.tangential_ratio_cap < 0.0:
            raise ValueError("tangential_ratio_cap must be non-negative")
        symmetric_dim = 2 * scalar_dim + 4
        self.damping = nn.Sequential(
            nn.Linear(symmetric_dim, scalar_dim), nn.SiLU(), nn.Linear(scalar_dim, 1)
        )
        self.contact = nn.Sequential(
            nn.Linear(symmetric_dim, scalar_dim), nn.SiLU(), nn.Linear(scalar_dim, 2)
        )

    @staticmethod
    def invariants(
        scalar: torch.Tensor,
        position: torch.Tensor,
        velocity: torch.Tensor,
        pairs: torch.Tensor,
        reference_position: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        src, dst = pairs
        relative = position[dst] - position[src]
        distance = torch.linalg.vector_norm(relative, dim=1, keepdim=True).clamp_min(1.0e-8)
        direction = relative / distance
        relative_velocity = velocity[dst] - velocity[src]
        normal_velocity = (relative_velocity * direction).sum(1, keepdim=True)
        if reference_position is None:
            stretch = torch.zeros_like(distance)
        else:
            reference_length = torch.linalg.vector_norm(
                reference_position[dst] - reference_position[src], dim=1, keepdim=True
            ).clamp_min(1.0e-8)
            stretch = distance / reference_length - 1.0
        features = torch.cat(
            [
                scalar[src] + scalar[dst],
                (scalar[src] - scalar[dst]).abs(),
                distance,
                stretch,
                normal_velocity,
                torch.linalg.vector_norm(relative_velocity, dim=1, keepdim=True),
            ],
            dim=1,
        )
        return features, direction, relative_velocity, normal_velocity

    @staticmethod
    def scatter_pair(force_on_src: torch.Tensor, pairs: torch.Tensor, count: int) -> torch.Tensor:
        result = force_on_src.new_zeros((count, 3))
        result.index_add_(0, pairs[0], force_on_src)
        result.index_add_(0, pairs[1], -force_on_src)
        return result

    @staticmethod
    def reduced_mass(mass: torch.Tensor, pairs: torch.Tensor) -> torch.Tensor:
        """Symmetric pair mass keeps learned accelerations mesh-scale stable."""

        nodal_mass = mass.reshape(-1)
        source_mass = nodal_mass[pairs[0]]
        target_mass = nodal_mass[pairs[1]]
        return (
            2.0
            * source_mass
            * target_mass
            / (source_mass + target_mass).clamp_min(torch.finfo(nodal_mass.dtype).tiny)
        )[:, None]

    @staticmethod
    def pair_normalization(pairs: torch.Tensor, count: int) -> torch.Tensor:
        """Mean-aggregate pair impulses without breaking action--reaction."""

        degree = torch.bincount(
            torch.cat([pairs[0], pairs[1]]), minlength=int(count)
        )
        pair_degree = torch.maximum(degree[pairs[0]], degree[pairs[1]])
        return pair_degree.clamp_min(1).to(dtype=torch.float32)[:, None].reciprocal()

    def mesh_damping(
        self,
        scalar: torch.Tensor,
        position: torch.Tensor,
        velocity: torch.Tensor,
        mesh_pairs: torch.Tensor,
        reference_position: torch.Tensor,
        nodal_mass: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        if mesh_pairs.numel() == 0:
            zero = position.new_zeros((position.shape[0], 3))
            return zero, position.new_zeros(())
        features, direction, _, normal_velocity = self.invariants(
            scalar, position, velocity, mesh_pairs, reference_position
        )
        coefficient = F.softplus(self.damping(features))
        force_src = coefficient * normal_velocity * direction
        pair_mass = None
        pair_weight = self.pair_normalization(mesh_pairs, position.shape[0]).to(
            force_src.dtype
        )
        force_src = force_src * pair_weight
        if nodal_mass is not None:
            pair_mass = self.reduced_mass(nodal_mass, mesh_pairs)
            force_src = force_src * pair_mass
        force = self.scatter_pair(force_src, mesh_pairs, position.shape[0])
        dissipation_density = coefficient * normal_velocity.square() * pair_weight
        if pair_mass is not None:
            dissipation_density = dissipation_density * pair_mass
        dissipation = dissipation_density.sum()
        return force, dissipation

    def contact_force(
        self,
        scalar: torch.Tensor,
        position: torch.Tensor,
        velocity: torch.Tensor,
        contact_pairs: torch.Tensor,
        radius: float,
        nodal_mass: torch.Tensor | None = None,
        reference_position: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if contact_pairs.numel() == 0:
            zero = position.new_zeros((position.shape[0], 3))
            scalar_zero = position.new_zeros(())
            return zero, scalar_zero, scalar_zero
        features, direction, relative_velocity, normal_velocity = self.invariants(
            scalar,
            position,
            velocity,
            contact_pairs,
            reference_position,
        )
        raw = self.contact(features)
        distance = features[:, -4:-3]
        if reference_position is None:
            contact_distance = torch.full_like(distance, float(radius))
        else:
            src, dst = contact_pairs
            reference_distance = torch.linalg.vector_norm(
                reference_position[dst] - reference_position[src],
                dim=1,
                keepdim=True,
            )
            contact_distance = reference_distance.clamp_max(float(radius))
        penetration = (
            (contact_distance - distance)
            / contact_distance.clamp_min(1.0e-8)
        ).clamp_min(0.0)
        normal_magnitude = F.softplus(raw[:, :1]) * penetration
        normal_force_src = -normal_magnitude * direction
        tangential_velocity = relative_velocity - normal_velocity * direction
        tangential_coefficient = F.softplus(raw[:, 1:2])
        tangential_speed = torch.linalg.vector_norm(
            tangential_velocity, dim=1, keepdim=True
        )
        candidate_tangent = (
            tangential_coefficient * tangential_speed * penetration
        )
        tangent_cap = self.tangential_ratio_cap * normal_magnitude
        bounded_tangent = tangent_cap * torch.tanh(
            candidate_tangent / tangent_cap.clamp_min(1.0e-8)
        )
        tangential_direction = tangential_velocity / tangential_speed.clamp_min(
            1.0e-8
        )
        tangential_force_src = bounded_tangent * tangential_direction
        force_src = normal_force_src + tangential_force_src
        pair_mass = None
        pair_weight = self.pair_normalization(contact_pairs, position.shape[0]).to(
            force_src.dtype
        )
        force_src = force_src * pair_weight
        if nodal_mass is not None:
            pair_mass = self.reduced_mass(nodal_mass, contact_pairs)
            force_src = force_src * pair_mass
        force = self.scatter_pair(force_src, contact_pairs, position.shape[0])
        dissipation_density = (
            bounded_tangent
            * tangential_speed
            * pair_weight
        )
        if pair_mass is not None:
            dissipation_density = dissipation_density * pair_mass
        dissipation = dissipation_density.sum()
        return force, penetration.max(), dissipation


class CHPGNS(nn.Module):
    """Hierarchical potential simulator whose stress and dynamics share mechanics."""

    checkpoint_schema_version = 2
    dynamics_schema_version = 7
    residual_parameterization = "acceleration_reference_v1"
    residual_gate = "local_topology_v1"

    def __init__(self, cfg: dict[str, Any], material_dim: int = 0) -> None:
        super().__init__()
        model_cfg = cfg.get("model", {})
        self.scalar_dim = int(model_cfg.get("scalar_dim", 96))
        self.vector_dim = int(model_cfg.get("vector_dim", 16))
        self.cell_dim = int(model_cfg.get("cell_dim", 64))
        self.material_dim = int(material_dim)
        self.contact_radius = float(get_cfg(cfg, "contact.radius", 0.03))
        self.contact_enabled = bool(get_cfg(cfg, "contact.enabled", True))
        self.contact_max_neighbors = int(get_cfg(cfg, "contact.max_neighbors", 32))
        self.refresh_contact_pairs_each_substep = bool(
            get_cfg(cfg, "contact.refresh_each_substep", True)
        )
        self.contact_substeps = int(model_cfg.get("contact_substeps", 2))
        self.residual_acceleration_reference = float(
            model_cfg.get("residual_acceleration_reference", 1.9e-4)
        )
        self.residual_acceleration_cap = float(
            model_cfg.get("residual_acceleration_cap", 3.0e-3)
        )
        self.integration_minimum_j = float(
            model_cfg.get("integration_minimum_j", 1.0e-4)
        )
        self.integration_maximum_i2_bar = float(
            model_cfg.get("integration_maximum_i2_bar", 1.0e6)
        )
        self.integration_backtracks = int(
            model_cfg.get("integration_backtracks", 8)
        )
        self.residual_activity_scale = float(
            model_cfg.get("residual_activity_scale", 1.0e-2)
        )
        self.residual_activity_diffusion_steps = int(
            model_cfg.get("residual_activity_diffusion_steps", 2)
        )
        if self.residual_acceleration_reference <= 0.0:
            raise ValueError("residual_acceleration_reference must be positive")
        if self.residual_acceleration_cap <= 0.0:
            raise ValueError("residual_acceleration_cap must be positive")
        if self.residual_activity_scale <= 0.0:
            raise ValueError("residual_activity_scale must be positive")
        self.normalize_potential_scale = bool(
            model_cfg.get("normalize_potential_scale", True)
        )
        initial_stress_scale = float(model_cfg.get("initial_stress_scale", 1.0))
        initial_mass_scale = float(model_cfg.get("initial_mass_scale", 1.0))
        initial_contact_scale = float(model_cfg.get("initial_contact_scale", 1.0e-3))
        initial_damping_scale = float(model_cfg.get("initial_damping_scale", 0.1))
        if min(
            initial_stress_scale,
            initial_mass_scale,
            initial_contact_scale,
            initial_damping_scale,
        ) <= 0.0:
            raise ValueError("initial physical scales must be positive")
        self.log_stress_scale = nn.Parameter(torch.tensor(math.log(initial_stress_scale)))
        self.log_mass_scale = nn.Parameter(torch.tensor(math.log(initial_mass_scale)))
        self.log_contact_scale = nn.Parameter(torch.tensor(math.log(initial_contact_scale)))
        self.log_damping_scale = nn.Parameter(torch.tensor(math.log(initial_damping_scale)))

        self.node_encoder = nn.Sequential(
            nn.Linear(6, self.scalar_dim),
            nn.SiLU(),
            nn.Linear(self.scalar_dim, self.scalar_dim),
            nn.LayerNorm(self.scalar_dim),
        )
        self.vector_encoder = VectorChannelLinear(4, self.vector_dim)
        self.processor = HierarchicalScalarVectorProcessor(
            self.scalar_dim,
            self.vector_dim,
            activation_checkpointing=bool(
                model_cfg.get("activation_checkpointing", True)
            ),
        )
        cell_input_dim = self.scalar_dim + 6 + self.material_dim
        self.cell_encoder = nn.Sequential(
            nn.Linear(cell_input_dim, self.cell_dim),
            nn.SiLU(),
            nn.Linear(self.cell_dim, self.cell_dim),
            nn.LayerNorm(self.cell_dim),
        )
        self.cell_blocks = nn.ModuleList(
            [
                CellNodeBlock(self.scalar_dim, self.vector_dim, self.cell_dim)
                for _ in range(4)
            ]
        )
        self.force_heads = PairForceHeads(
            self.scalar_dim,
            tangential_ratio_cap=float(
                model_cfg.get("contact_tangential_ratio_cap", 1.0)
            ),
        )
        self.residual_channel = VectorChannelLinear(self.vector_dim, 1)
        self.potential = AnalyticPotential(
            order=int(model_cfg.get("potential_order", 2)),
            i1_init=model_cfg.get("potential_i1_init", 0.5),
            i2_init=model_cfg.get("potential_i2_init", 0.1),
            j_init=model_cfg.get("potential_j_init", 1.0),
            log_j_init=float(model_cfg.get("potential_log_j_init", 1.0)),
            fiber_order=int(model_cfg.get("fiber_order", 0)),
            fiber_init=model_cfg.get("potential_fiber_init", 0.1),
            inversion_stiffness=float(model_cfg.get("inversion_stiffness", 10.0)),
            minimum_j=float(model_cfg.get("minimum_j", 0.0)),
            determinant_eps=model_cfg.get("determinant_eps", None),
            minimum_coefficient=float(
                model_cfg.get("potential_minimum_coefficient", 1.0e-8)
            ),
        )
        self.material_coefficient_count = (
            3 * self.potential.order + 1 + self.potential.fiber_order
        )
        self.material_potential = None
        if self.material_dim:
            final = nn.Linear(32, self.material_coefficient_count)
            nn.init.zeros_(final.weight)
            nn.init.zeros_(final.bias)
            self.material_potential = nn.Sequential(
                nn.Linear(self.material_dim, 32),
                nn.SiLU(),
                final,
            )

    def material_coefficient_multipliers(
        self, material: torch.Tensor
    ) -> dict[str, torch.Tensor]:
        """Return positive per-cell multipliers for every potential basis."""

        if self.material_potential is None:
            return {}
        material = material.float()
        if material.ndim != 2 or material.shape[1] != self.material_dim:
            raise ValueError(
                f"Expected material features [M,{self.material_dim}], got "
                f"{tuple(material.shape)}"
            )
        signed_log = torch.sign(material) * torch.log1p(material.abs())
        raw = self.material_potential(signed_log)
        positive = F.softplus(raw).float() / math.log(2.0) + 1.0e-6
        offset = 0

        def take(width: int) -> torch.Tensor:
            nonlocal offset
            value = positive[:, offset : offset + width]
            offset += width
            return value

        result = {
            "i1": take(self.potential.order),
            "i2": take(self.potential.order),
            "j": take(self.potential.order),
            "log_j": take(1),
        }
        if self.potential.fiber_order:
            result["fiber"] = take(self.potential.fiber_order)
        if offset != self.material_coefficient_count:
            raise RuntimeError("material potential coefficient partition is inconsistent")
        return result

    def constitutive_fields(
        self,
        static: CHPStatic,
        position: torch.Tensor,
        *,
        deformation: torch.Tensor | None = None,
    ) -> ConstitutiveFields:
        """Evaluate stress, energy, and internal force from the same potential."""

        position = position.float()
        if deformation is None:
            deformation = deformation_gradient(position, static.cells, static.dm_inv)
        material = static.material_features.float()
        if material.shape[1] != self.material_dim:
            raise ValueError(
                f"Expected {self.material_dim} material features, got {material.shape[1]}"
            )
        fiber = static.fiber_direction if self.potential.fiber_order else None
        response = self.potential(
            deformation,
            fiber_direction=fiber,
            coefficient_multipliers=self.material_coefficient_multipliers(material),
        )
        physical_modulus = self.log_stress_scale.clamp(-20.0, 30.0).exp()
        potential_scale = (
            self.potential.i1_coefficients[0].clamp_min(1.0e-12)
            if self.normalize_potential_scale
            else physical_modulus.new_ones(())
        )
        stress_scale = physical_modulus / potential_scale
        first_piola = response.first_piola * stress_scale
        cauchy = response.cauchy_stress * stress_scale
        energy_density = response.energy_density * stress_scale
        internal = assemble_internal_force(
            first_piola,
            static.cells,
            static.volume,
            static.shape_gradients,
            static.num_nodes,
        )
        return ConstitutiveFields(
            deformation=deformation,
            first_piola=first_piola,
            cauchy_stress=cauchy,
            energy_density=energy_density,
            internal_force=internal,
            inversion_barrier=response.inversion_barrier,
        )

    def nodal_stress_at(
        self, static: CHPStatic, position: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Return potential-derived nodal von-Mises and full cell stress."""

        fields = self.constitutive_fields(static, position)
        cell_vm = von_mises(fields.cauchy_stress)
        nodal = project_cell_to_nodes(
            cell_vm[:, None],
            static.cells,
            static.num_nodes,
            weights=static.volume,
        )
        return nodal, fields.cauchy_stress

    def forward(
        self,
        static: CHPStatic,
        state: CHPState,
        *,
        contact_pairs: torch.Tensor | None = None,
        external_force: torch.Tensor | None = None,
        dt: float | torch.Tensor = 1.0,
        time_fraction: float | torch.Tensor = 0.0,
        prescribed_position: torch.Tensor | None = None,
        prescribed_velocity: torch.Tensor | None = None,
        detach_pair_force_features: bool = False,
    ) -> PhysicalStep:
        position = state.position.float()
        velocity = state.velocity.float()
        reference = static.reference_position.float()
        displacement = position - reference
        if external_force is None:
            external_force = torch.zeros_like(position)
        else:
            external_force = external_force.float()
        step_dt = torch.as_tensor(dt, device=position.device, dtype=position.dtype)
        boundary_target_velocity = torch.zeros_like(position)
        if bool(static.prescribed_mask.any().item()):
            if prescribed_position is not None:
                prescribed_target = (
                    prescribed_position.float() - position
                ) / step_dt
            elif prescribed_velocity is not None:
                prescribed_target = prescribed_velocity.float()
            else:
                prescribed_target = velocity
            boundary_target_velocity = torch.where(
                static.prescribed_mask[:, None],
                prescribed_target,
                boundary_target_velocity,
            )
        time = torch.as_tensor(time_fraction, device=position.device, dtype=position.dtype)
        scalar_input = torch.stack(
            [
                static.fixed_mask.float(),
                static.prescribed_mask.float(),
                (~(static.fixed_mask | static.prescribed_mask)).float(),
                torch.log1p(static.lumped_mass.float().reshape(-1)),
                torch.sin(2.0 * torch.pi * time).expand(position.shape[0]),
                torch.cos(2.0 * torch.pi * time).expand(position.shape[0]),
            ],
            dim=1,
        )
        scalar = self.node_encoder(scalar_input)
        vector_input = torch.stack(
            [
                displacement,
                velocity,
                external_force,
                boundary_target_velocity,
            ],
            dim=1,
        )
        vector = self.vector_encoder(vector_input)
        deformation = deformation_gradient(position, static.cells, static.dm_inv)
        strain = invariants(deformation)
        invariant_features = torch.stack(
            [
                strain.i1_bar - 3.0,
                strain.i2_bar - 3.0,
                strain.j - 1.0,
                torch.log(strain.j.clamp_min(1.0e-8)),
                strain.i1 - 3.0,
                strain.i2 - 3.0,
            ],
            dim=1,
        )
        cell_node = scalar[static.cells].mean(1)
        material = static.material_features.float()
        if material.shape[1] != self.material_dim:
            raise ValueError(
                f"Expected {self.material_dim} material features, got {material.shape[1]}"
            )
        cell = self.cell_encoder(torch.cat([cell_node, invariant_features, material], 1))
        # Encode local constitutive incidence before the topology hierarchy so
        # coarse propagation can transmit cell state over long graph distances.
        for block in self.cell_blocks[:2]:
            scalar, vector, cell = block(
                scalar, vector, cell, static.cells, position
            )
        scalar, vector = self.processor(scalar, vector, position, static.hierarchy)
        for block in self.cell_blocks[2:]:
            scalar, vector, cell = block(
                scalar, vector, cell, static.cells, position
            )

        initial_fields = self.constitutive_fields(
            static, position, deformation=deformation
        )
        mesh_pairs = unique_undirected_pairs(static.mesh_edge_index, static.num_nodes)
        if contact_pairs is None:
            contact_pairs = position.new_zeros((2, 0), dtype=torch.long)
        contact_pairs = unique_undirected_pairs(contact_pairs, static.num_nodes)
        mass_scale = self.log_mass_scale.clamp(-20.0, 50.0).exp()
        nodal_mass = static.lumped_mass.reshape(-1) * mass_scale
        contact_scale = self.log_contact_scale.clamp(-20.0, 10.0).exp()
        damping_scale = self.log_damping_scale.clamp(-20.0, 10.0).exp()
        raw_residual = self.residual_channel(vector)[:, 0]
        residual_norm = torch.linalg.vector_norm(raw_residual, dim=1, keepdim=True)
        cap_ratio = self.residual_acceleration_cap / max(
            self.residual_acceleration_reference, 1.0e-12
        )
        residual_acceleration = (
            self.residual_acceleration_reference
            * cap_ratio
            * torch.tanh(residual_norm / cap_ratio)
            * raw_residual
            / residual_norm.clamp_min(1.0e-8)
        )
        external_acceleration = external_force / nodal_mass[:, None]
        activity = (
            torch.linalg.vector_norm(displacement, dim=1, keepdim=True)
            + step_dt.abs()
            * torch.linalg.vector_norm(velocity, dim=1, keepdim=True)
            + step_dt.square()
            * torch.linalg.vector_norm(
                external_acceleration, dim=1, keepdim=True
            )
            + step_dt.abs()
            * torch.linalg.vector_norm(
                boundary_target_velocity, dim=1, keepdim=True
            )
        )
        activity = diffuse_node_activity(
            activity,
            static.mesh_edge_index,
            rounds=self.residual_activity_diffusion_steps,
        )
        activity_gate = torch.tanh(
            activity / max(self.residual_activity_scale, 1.0e-8)
        )
        dynamic_mask = ~(static.fixed_mask | static.prescribed_mask)
        activity_gate = activity_gate * dynamic_mask[:, None]
        residual_acceleration = residual_acceleration * activity_gate
        # The source dataset has no physical dt/density pair (meta.json stores
        # dt=0), so the bounded learned correction is identifiable as an
        # acceleration.  Multiplication by lumped mass preserves the public
        # force contract and keeps its state effect independent of the fitted
        # effective inertia scale.
        residual = residual_acceleration * nodal_mass[:, None]
        active_prescribed_mask = (
            static.prescribed_mask
            if bool(static.prescribed_mask.any().item())
            else None
        )
        substep_dt = step_dt / max(self.contact_substeps, 1)
        current_position = position
        current_velocity = velocity
        external_work = position.new_zeros(())
        boundary_work = position.new_zeros(())
        residual_work = position.new_zeros(())
        damping_dissipation = position.new_zeros(())
        contact_dissipation = position.new_zeros(())
        projection_dissipation = position.new_zeros(())
        integration_domain_penalty = position.new_zeros(())
        max_penetration = position.new_zeros(())
        minimum_update_scale = position.new_ones(())
        integration_valid = torch.ones((), dtype=torch.bool, device=position.device)
        free_mask = ~static.fixed_mask
        if active_prescribed_mask is not None:
            free_mask = free_mask & ~active_prescribed_mask
        damping = torch.zeros_like(position)
        contact = torch.zeros_like(position)
        total_force = torch.zeros_like(position)
        current_fields = initial_fields
        force_scalar = scalar.detach() if detach_pair_force_features else scalar
        active_contact_pairs = contact_pairs
        for substep in range(max(self.contact_substeps, 1)):
            if substep:
                current_fields = self.constitutive_fields(static, current_position)
                if (
                    self.contact_enabled
                    and self.refresh_contact_pairs_each_substep
                    and current_position.is_cuda
                ):
                    active_contact_pairs = radius_contact_pairs(
                        current_position,
                        static.mesh_edge_index,
                        static.fixed_mask,
                        self.contact_radius,
                        max_neighbors=self.contact_max_neighbors,
                        prescribed_mask=static.prescribed_mask,
                        surface_mask=static.contact_surface_mask,
                    )
            damping, damping_rate = self.force_heads.mesh_damping(
                force_scalar,
                current_position,
                current_velocity,
                mesh_pairs,
                reference,
                nodal_mass,
            )
            contact, penetration, contact_rate = self.force_heads.contact_force(
                force_scalar,
                current_position,
                current_velocity,
                active_contact_pairs,
                self.contact_radius,
                nodal_mass,
                reference,
            )
            damping = damping * damping_scale
            damping_rate = damping_rate * damping_scale
            contact = contact * contact_scale
            contact_rate = contact_rate * contact_scale
            max_penetration = torch.maximum(max_penetration, penetration)
            total_force = (
                current_fields.internal_force
                + damping
                + contact
                + residual
                + external_force
            )
            substep_target = None
            if prescribed_position is not None:
                fraction = float(substep + 1) / max(self.contact_substeps, 1)
                substep_target = position + fraction * (
                    prescribed_position.float() - position
                )
            integrated = semi_implicit_step(
                current_position,
                current_velocity,
                total_force,
                nodal_mass,
                substep_dt,
                substeps=1,
                fixed_mask=static.fixed_mask,
                prescribed_mask=active_prescribed_mask,
                prescribed_position=substep_target,
                prescribed_velocity=prescribed_velocity,
            )
            proposal_penalty = tetrahedral_domain_penalty(
                integrated.position,
                static.cells,
                static.dm_inv,
                minimum_j=self.integration_minimum_j,
                maximum_i2_bar=self.integration_maximum_i2_bar,
            )
            integration_domain_penalty = torch.maximum(
                integration_domain_penalty, proposal_penalty
            )
            accepted_position, update_scale, update_valid = backtrack_tetrahedral_update(
                current_position,
                integrated.position,
                static.cells,
                static.dm_inv,
                fixed_mask=static.fixed_mask,
                prescribed_mask=active_prescribed_mask,
                minimum_j=self.integration_minimum_j,
                maximum_i2_bar=self.integration_maximum_i2_bar,
                max_backtracks=self.integration_backtracks,
            )
            minimum_update_scale = torch.minimum(minimum_update_scale, update_scale)
            integration_valid = integration_valid & update_valid
            derived_velocity = (accepted_position - current_position) / substep_dt
            accepted_velocity = torch.where(
                free_mask[:, None], derived_velocity, integrated.velocity
            )
            proposal_kinetic = 0.5 * (
                nodal_mass[:, None] * integrated.velocity.square()
            ).sum()
            accepted_kinetic = 0.5 * (
                nodal_mass[:, None] * accepted_velocity.square()
            ).sum()
            projection_dissipation = projection_dissipation + (
                proposal_kinetic - accepted_kinetic
            ).clamp_min(0.0)
            damping_dissipation = damping_dissipation + damping_rate * substep_dt
            contact_dissipation = contact_dissipation + contact_rate * substep_dt
            current_position = accepted_position
            current_velocity = accepted_velocity

        # Each contact substep already applies symplectic Euler with dt/S.
        # Keep the accumulated trajectory instead of reconstructing x[t+1]
        # from only the final velocity, which would discard the first
        # substep's position and no longer represent the force refresh path.
        acceleration = (current_velocity - velocity) / step_dt
        full_step_displacement = current_position - position
        external_work = (external_force * full_step_displacement).sum()
        residual_work = (residual * full_step_displacement).sum()
        if active_prescribed_mask is not None:
            reaction = nodal_mass[:, None] * acceleration - total_force
            boundary_work = (
                reaction[active_prescribed_mask]
                * full_step_displacement[active_prescribed_mask]
            ).sum()
        final_fields = self.constitutive_fields(static, current_position)
        kinetic_before = 0.5 * (
            static.lumped_mass.reshape(-1, 1)
            * mass_scale
            * velocity.square()
        ).sum()
        kinetic_after = 0.5 * (
            static.lumped_mass.reshape(-1, 1) * current_velocity.square() * mass_scale
        ).sum()
        potential_before = (static.volume * initial_fields.energy_density).sum()
        next_cell_vm = von_mises(final_fields.cauchy_stress)
        nodal_stress = project_cell_to_nodes(
            next_cell_vm[:, None],
            static.cells,
            static.num_nodes,
            weights=static.volume,
        )
        potential_after = (static.volume * final_fields.energy_density).sum()
        energy_balance = (
            kinetic_after
            + potential_after
            - kinetic_before
            - potential_before
            - external_work
            - boundary_work
            - residual_work
            + damping_dissipation
            + contact_dissipation
            + projection_dissipation
        )
        return PhysicalStep(
            next_position=current_position,
            next_velocity=current_velocity,
            acceleration=acceleration,
            nodal_stress=nodal_stress,
            cell_stress_tensor=final_fields.cauchy_stress,
            internal_force=initial_fields.internal_force,
            contact_force=contact,
            damping_force=damping,
            residual_force=residual,
            energy_diagnostics={
                "potential": potential_before,
                "potential_after": potential_after,
                "kinetic": kinetic_before,
                "kinetic_after": kinetic_after,
                "external_work": external_work,
                "boundary_work": boundary_work,
                "residual_work": residual_work,
                "work_energy_balance": energy_balance,
                "damping_dissipation": damping_dissipation,
                "contact_dissipation": contact_dissipation,
                "projection_dissipation": projection_dissipation,
                "max_penetration": max_penetration,
                "negative_j": torch.maximum(
                    torch.maximum(
                        initial_fields.inversion_barrier.mean(),
                        final_fields.inversion_barrier.mean(),
                    ),
                    integration_domain_penalty,
                ),
                "residual_norm": residual_acceleration.square().mean().sqrt(),
                "residual_reference": position.new_tensor(
                    self.residual_acceleration_reference
                ),
                "residual_activity_mean": activity_gate.mean(),
                "residual_activity_max": activity_gate.max(),
                "boundary_drive_max": torch.linalg.vector_norm(
                    boundary_target_velocity, dim=1
                ).max(),
                "integration_update_scale": minimum_update_scale,
                "integration_valid": integration_valid.to(position.dtype),
                "integration_domain_penalty": integration_domain_penalty,
                "stress_scale": self.log_stress_scale.clamp(-20.0, 30.0).exp(),
                "mass_scale": mass_scale,
                "contact_scale": contact_scale,
                "damping_scale": damping_scale,
                "contact_pair_count": position.new_tensor(
                    active_contact_pairs.shape[1]
                ),
            },
        )


def unique_undirected_pairs(edge_index: torch.Tensor, num_nodes: int) -> torch.Tensor:
    if edge_index.numel() == 0:
        return torch.zeros((2, 0), dtype=torch.long, device=edge_index.device)
    src = torch.minimum(edge_index[0].long(), edge_index[1].long())
    dst = torch.maximum(edge_index[0].long(), edge_index[1].long())
    keep = src != dst
    encoded = torch.unique(src[keep] * int(num_nodes) + dst[keep], sorted=True)
    return torch.stack([encoded // int(num_nodes), encoded % int(num_nodes)], dim=0)


def diffuse_node_activity(
    activity: torch.Tensor,
    edge_index: torch.Tensor,
    *,
    rounds: int = 2,
) -> torch.Tensor:
    """Diffuse a non-negative node gate locally without a graph-wide broadcast."""

    if activity.ndim != 2 or activity.shape[1] != 1:
        raise ValueError("activity must have shape [N, 1]")
    if edge_index.numel() == 0 or int(rounds) <= 0:
        return activity
    src, dst = edge_index.long()
    degree = torch.bincount(dst, minlength=activity.shape[0]).to(activity.dtype)
    degree = degree[:, None] + 1.0
    value = activity
    for _ in range(int(rounds)):
        aggregate = value.clone()
        aggregate.index_add_(0, dst, value[src])
        value = aggregate / degree
    return value


def tetrahedral_domain_penalty(
    position: torch.Tensor,
    cells: torch.Tensor,
    dm_inv: torch.Tensor,
    *,
    minimum_j: float = 1.0e-4,
    maximum_i2_bar: float = 1.0e6,
) -> torch.Tensor:
    """Differentiable penalty on a raw proposal before safety projection."""

    state = invariants(deformation_gradient(position, cells, dm_inv))
    proposal_j = torch.nan_to_num(
        state.j,
        nan=-1.0e3,
        posinf=1.0e3,
        neginf=-1.0e3,
    )
    j_violation = F.relu(float(minimum_j) - proposal_j)
    overflow = float(maximum_i2_bar) * math.exp(10.0)
    proposal_i2 = torch.nan_to_num(
        state.i2_bar,
        nan=overflow,
        posinf=overflow,
        neginf=overflow,
    ).clamp_min(1.0e-12)
    i2_violation = F.relu(
        torch.log(proposal_i2 / max(float(maximum_i2_bar), 1.0e-12))
    )
    return (
        j_violation.square().mean()
        + j_violation.square().max()
        + i2_violation.square().mean()
        + i2_violation.square().max()
    )


def backtrack_tetrahedral_update(
    current_position: torch.Tensor,
    proposed_position: torch.Tensor,
    cells: torch.Tensor,
    dm_inv: torch.Tensor,
    *,
    fixed_mask: torch.Tensor | None = None,
    prescribed_mask: torch.Tensor | None = None,
    minimum_j: float = 1.0e-4,
    maximum_i2_bar: float = 1.0e6,
    max_backtracks: int = 8,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Select the largest admissible free-node update in one batched GPU pass.

    The scalar scale and validity flag remain device tensors so this safeguard
    does not introduce a CUDA-to-host synchronization at every rollout step.
    Constrained nodes retain their proposed values; consequently ``valid`` can
    be false when a prescribed update itself leaves the constitutive domain.
    """

    free = torch.ones(
        current_position.shape[0], dtype=torch.bool, device=current_position.device
    )
    if fixed_mask is not None:
        free &= ~fixed_mask.bool()
    if prescribed_mask is not None:
        free &= ~prescribed_mask.bool()
    delta = proposed_position - current_position
    exponent = torch.arange(
        max(int(max_backtracks), 0) + 1,
        device=current_position.device,
        dtype=current_position.dtype,
    )
    scales = torch.pow(current_position.new_tensor(0.5), exponent)
    scales = torch.cat([scales, scales.new_zeros(1)])
    with torch.no_grad():
        candidate = (
            current_position.detach()[None]
            + scales[:, None, None] * delta.detach()[None]
        )
        candidate = torch.where(
            free[None, :, None], candidate, proposed_position.detach()[None]
        )
        state = invariants(deformation_gradient(candidate, cells, dm_inv))
        valid = (
            torch.isfinite(state.j).all(dim=1)
            & torch.isfinite(state.i2_bar).all(dim=1)
            & (state.j.amin(dim=1) >= float(minimum_j))
            & (state.i2_bar.amax(dim=1) <= float(maximum_i2_bar))
        )
        has_valid = valid.any()
        first_valid = valid.to(torch.int64).argmax()
        accepted_scale = torch.where(
            has_valid, scales[first_valid], scales.new_zeros(())
        )
    accepted = current_position + accepted_scale * delta
    accepted = torch.where(free[:, None], accepted, proposed_position)
    return accepted, accepted_scale, has_valid


def tetra_surface_node_mask(cells: torch.Tensor, num_nodes: int) -> torch.Tensor:
    """Return nodes incident to a boundary face of a tetrahedral complex."""

    cells = torch.as_tensor(cells, dtype=torch.long)
    if cells.ndim != 2 or cells.shape[1] != 4:
        raise ValueError("cells must have shape [M, 4]")
    faces = torch.cat(
        [
            cells[:, [0, 1, 2]],
            cells[:, [0, 1, 3]],
            cells[:, [0, 2, 3]],
            cells[:, [1, 2, 3]],
        ],
        dim=0,
    ).sort(dim=1).values
    encoded = (faces[:, 0] * int(num_nodes) + faces[:, 1]) * int(
        num_nodes
    ) + faces[:, 2]
    _, inverse, counts = torch.unique(
        encoded, sorted=False, return_inverse=True, return_counts=True
    )
    boundary_faces = faces[counts[inverse] == 1]
    mask = torch.zeros(int(num_nodes), dtype=torch.bool, device=cells.device)
    if boundary_faces.numel():
        mask[boundary_faces.reshape(-1)] = True
    return mask


def build_chp_static(
    case,
    device: torch.device | str,
    *,
    hierarchy: TopologyHierarchy | None = None,
    material_dim: int | None = None,
) -> CHPStatic:
    """Move one constitutive case and its cached topology hierarchy to a device."""

    def tensor(value, dtype):
        return torch.from_numpy(np.array(value, copy=True)).to(device=device, dtype=dtype)

    reference = tensor(case.nodes, torch.float32)
    cells = tensor(case.cells, torch.long)
    explicit_surface_mask = np.asarray(
        getattr(case, "contact_surface_mask", np.zeros((0,), dtype=bool)),
        dtype=bool,
    )
    if explicit_surface_mask.shape == (case.num_nodes,):
        surface_mask = tensor(explicit_surface_mask, torch.bool)
    elif explicit_surface_mask.size == 0:
        surface_mask = tetra_surface_node_mask(
            torch.from_numpy(np.array(case.cells, dtype=np.int64, copy=True)),
            case.num_nodes,
        ).to(device=device)
    else:
        raise ValueError(
            f"{case.case_id}: contact_surface_mask must be empty or have shape "
            f"[{case.num_nodes}]"
        )
    mesh_edges = tensor(case.mesh_edge_index, torch.long)
    hierarchy = (hierarchy or build_case_hierarchy(case)).to(device)
    material_features = np.array(case.material_features, dtype=np.float32, copy=True)
    if material_dim is not None:
        if material_features.shape[1] > int(material_dim):
            raise ValueError(
                f"{case.case_id}: material feature width exceeds model width "
                f"({material_features.shape[1]} > {material_dim})"
            )
        if material_features.shape[1] < int(material_dim):
            material_features = np.pad(
                material_features,
                ((0, 0), (0, int(material_dim) - material_features.shape[1])),
            )
    return CHPStatic(
        reference_position=reference,
        cells=cells,
        mesh_edge_index=mesh_edges,
        dm_inv=tensor(case.dm_inv, torch.float32),
        volume=tensor(case.reference_volume.reshape(-1), torch.float32),
        shape_gradients=tensor(case.shape_gradients, torch.float32),
        lumped_mass=tensor(case.lumped_mass.reshape(-1), torch.float32),
        fixed_mask=tensor(case.fixed_mask, torch.bool),
        prescribed_mask=tensor(case.prescribed_mask, torch.bool),
        contact_surface_mask=surface_mask,
        material_features=tensor(material_features, torch.float32),
        fiber_direction=tensor(case.fiber_direction, torch.float32),
        hierarchy=hierarchy,
    )


def build_case_hierarchy(case) -> TopologyHierarchy:
    from valgraphnet.hierarchy import build_topology_hierarchy

    return build_topology_hierarchy(
        case.num_nodes,
        torch.from_numpy(np.array(case.mesh_edge_index, dtype=np.int64, copy=True)),
    )


def radius_contact_pairs(
    position: torch.Tensor,
    mesh_edge_index: torch.Tensor,
    fixed_mask: torch.Tensor,
    radius: float,
    max_neighbors: int = 32,
    prescribed_mask: torch.Tensor | None = None,
    surface_mask: torch.Tensor | None = None,
) -> torch.Tensor:
    """Build exact bounded contact pairs on CUDA using PhysicsNeMo Warp search."""

    if not position.is_cuda:
        raise ValueError("radius_contact_pairs requires CUDA positions")
    from physicsnemo.nn.functional import radius_search

    count = int(position.shape[0])
    points = position.detach().float()
    neighbors = radius_search(
        points,
        points,
        radius=float(radius),
        max_points=count,
        return_dists=False,
        return_points=False,
    ).long()
    sources = torch.arange(count, device=position.device)[:, None].expand_as(neighbors)
    adjacency = torch.zeros((count, count), dtype=torch.bool, device=position.device)
    adjacency[mesh_edge_index[0], mesh_edge_index[1]] = True
    valid = (neighbors != sources) & ~adjacency[sources, neighbors]
    valid &= ~(fixed_mask[sources] & fixed_mask[neighbors])
    if prescribed_mask is not None and bool(prescribed_mask.any().item()):
        prescribed_mask = prescribed_mask.to(device=position.device, dtype=torch.bool)
        # In deforming_plate the prescribed tetrahedra form the rigid indenter.
        # Only cross-body pairs are contacts; nearby non-edge vertices inside
        # either tetrahedral body must never repel one another.
        valid &= prescribed_mask[sources] ^ prescribed_mask[neighbors]
    if surface_mask is not None:
        surface_mask = surface_mask.to(device=position.device, dtype=torch.bool)
        valid &= surface_mask[sources] & surface_mask[neighbors]
    distance_sq = ((points[sources] - points[neighbors]) ** 2).sum(-1)
    valid &= distance_sq <= float(radius) ** 2
    distance_sq = distance_sq.masked_fill(~valid, torch.inf)
    keep_count = min(int(max_neighbors), count)
    best_distance, positions = torch.topk(
        distance_sq, keep_count, dim=1, largest=False, sorted=True
    )
    best_neighbors = neighbors.gather(1, positions)
    keep = torch.isfinite(best_distance)
    src = sources[:, :keep_count][keep]
    dst = best_neighbors[keep]
    return unique_undirected_pairs(torch.stack([src, dst]), count)
